### ISSUE TITLE
运行时提示找不到库

### ISSUE THREAD

**Issue by coolJason** [Airsaid/sample-gradle-plugin#12]
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.momodae.RecyclerViewLibrary2:adapter:1.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/momodae/RecyclerViewLibrary2/adapter/1.0.1/adapter-1.0.1.pom
       - https://repo.maven.apache.org/maven2/com/github/momodae/RecyclerViewLibrary2/adapter/1.0.1/adapter-1.0.1.pom
     Required by:
         project :app > com.airsaid:sample-extension:1.1.2
   > Could not find me.jfenn.ColorPickerDialog:base:0.2.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/me/jfenn/ColorPickerDialog/base/0.2.2/base-0.2.2.pom
       - https://repo.maven.apache.org/maven2/me/jfenn/ColorPickerDialog/base/0.2.2/base-0.2.2.pom
     Required by:
         project :app > com.airsaid:sample-extension:1.1.2

**Comment by Airsaid** [comment]
需要添加一下 jitpack 仓库（后续会将依赖的这两个库给移除掉或替换掉）：
```
dependencyResolutionManagement {
  repositories {
    ......
    maven("https://jitpack.io")
  }
}
```
